// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqiksiuwagxeaqdblkzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxaWtzaXV3YWd4ZWFxZGJsa3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTAzNTcsImV4cCI6MjA2NTY4NjM1N30.DlEDu92XMvmdIjtoqyMTx7BuHOC7Ze_jINHDoHi8SwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);